version: '3'
services:
  broker:
    build: ./broker
    ports: ["8080:8080"]
    volumes:
      - ./database:/app/database
  engine:
    build: ./engine
    volumes: ["./engine/algos:/app/algos"]
  executor:
    build: ./executor
  db:
    image: keinos/sqlite3
    volumes: ["./database:/db"]
  frontend:
    build: ./user/blink
    ports: ["80:80"]