events {
    worker_connections 1024;
}

http {
    upstream datafeed {
        server localhost:9000;
    }
    upstream executor {
        server localhost:9001;
    }
    server {
        listen 80;
        location /ws/datafeed {
            proxy_pass http://datafeed;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        location /ws/executor {
            proxy_pass http://executor;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        location / { return 404; }
    }
}
}