events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /ws/executor {
            proxy_pass http://localhost:9001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /api/research {
            rewrite ^/api/research/(.*) /$1 break;
            proxy_pass http://localhost:5001;
            proxy_set_header Host $host;
        }

        location / {
            return 404;
        }
    }
}
