services:
  - type: web
    name: blink-frontend
    runtime: docker
    dockerfilePath: user/blink/dockerfile
    dockerContext: .
    plan: free

  - type: web
    name: blink-datafeed
    runtime: docker
    dockerfilePath: datafeed/dockerfile
    dockerContext: .
    plan: free
    port: 9000

  - type: pserv
    name: blink-broker
    runtime: docker
    dockerfilePath: broker/dockerfile
    dockerContext: .
    plan: starter
    port: 8080

  - type: pserv
    name: blink-executor
    runtime: docker
    dockerfilePath: executor/dockerfile
    dockerContext: .
    plan: starter
    port: 9001

  - type: web
    name: blink-engine
    runtime: docker
    dockerfilePath: engine/dockerfile
    dockerContext: .
    plan: free